<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[User Name is successfully entered]]>
    </line>
    <line>
      <![CDATA[Password is successfully entered]]>
    </line>
    <line>
      <![CDATA[Pin entered successfully]]>
    </line>
  </reporter-output>
  <suite started-at="2021-08-03T12:55:52 IST" name="Default suite" finished-at="2021-08-03T12:56:16 IST" duration-ms="24448">
    <groups>
    </groups>
    <test started-at="2021-08-03T12:55:52 IST" name="Default test" finished-at="2021-08-03T12:56:16 IST" duration-ms="24448">
      <class name="Kite_property">
        <test-method is-config="true" signature="BrowserInvoke()[pri:0, instance:Kite_property@5562c41e]" started-at="2021-08-03T12:55:52 IST" name="BrowserInvoke" finished-at="2021-08-03T12:56:06 IST" duration-ms="14310" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserInvoke -->
        <test-method is-config="true" signature="LoginTokite()[pri:0, instance:Kite_property@5562c41e]" started-at="2021-08-03T12:56:06 IST" name="LoginTokite" finished-at="2021-08-03T12:56:11 IST" duration-ms="4952" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[User Name is successfully entered]]>
            </line>
            <line>
              <![CDATA[Password is successfully entered]]>
            </line>
            <line>
              <![CDATA[Pin entered successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- LoginTokite -->
        <test-method signature="UserIdvalidation()[pri:0, instance:Kite_property@5562c41e]" started-at="2021-08-03T12:56:11 IST" name="UserIdvalidation" finished-at="2021-08-03T12:56:14 IST" duration-ms="2749" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Year@123] but found [DV1510]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Year@123] but found [DV1510]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Kite_property.UserIdvalidation(Kite_property.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserIdvalidation -->
        <test-method is-config="true" signature="LogOut(org.testng.ITestResult)[pri:0, instance:Kite_property@5562c41e]" started-at="2021-08-03T12:56:14 IST" name="LogOut" finished-at="2021-08-03T12:56:16 IST" duration-ms="2076" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=UserIdvalidation status=FAILURE method=Kite_property.UserIdvalidation()[pri:0, instance:Kite_property@5562c41e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogOut -->
        <test-method is-config="true" signature="CloseBrowser()[pri:0, instance:Kite_property@5562c41e]" started-at="2021-08-03T12:56:16 IST" name="CloseBrowser" finished-at="2021-08-03T12:56:16 IST" duration-ms="267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- Kite_property -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
